AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
Metrics/MethodLength:
  Exclude:
    - "ConsoleMenu::MainMenu::Main#check_menu"
